meta_product_name: "Soffie"
meta_title: "Soffie - your next book is already in your pile"
meta_description: "For all those « rats de bibliothèques » and their ever growing piles of unread books and missed reading opportunities.
Soffie helps you find your perfect book from your pile, fitting your busy schedule & mood."
meta_image: "https://res.cloudinary.com/camvillard/image/upload/v1543358545/soffie/book-3.jpg"                       # should exist in `app/assets/images/`
twitter_account: "@giveabooksoffie"
